server:
  port: 8889

  servlet:
    context-path: /
spring:
  application:
    name: client-api

  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  cache:
    type: redis
  #jackson json解析
  jackson:
    time-zone: GMT+8
    serialization:
      #关闭jackson 对json做解析
      fail-on-empty-beans: false

  # Redis
  redis:
    host: 114.132.229.139
    port: 6379
    password: 123456
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 20
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池中的最小空闲连接 默认 8
        min-idle: 8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: dp_iot
    password: PbyWeLM4tPWAATLJ
    url: jdbc:mysql://101.34.64.87:3306/dp_iot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

# 忽略TOKEN 鉴权 的url
ignored:
  urls:
    - /editor-app/**
    - /actuator**
    - /actuator/**
    - /MP_verify_qSyvBPhDsPdxvOhC.txt
    - /weixin/**
    - /source/**
    - /buyer/payment/cashier/**
    - /buyer/payment/cashierRefund/**
    - /buyer/other/pageData/**
    - /buyer/other/article/**
    - /buyer/goods/**
    - /buyer/store/**
    - /buyer/passport/connect/**
    - /buyer/members/**
    - /buyer/passport/member/**
    - /buyer/passport/member/refresh/**
    - /buyer/promotion/pintuan/**
    - /buyer/promotion/seckill/**
    - /buyer/promotion/pointsGoods/**
    - /buyer/promotion/coupon
    - /buyer/member/evaluation/**/goodsEvaluation
    - /buyer/member/evaluation/**/evaluationNumber
    - /buyer/other/appVersion/**
    - /buyer/broadcast/studio/**
    - /druid/**
    - /swagger-ui.html
    - /doc.html
    - /swagger-resources/**
    - /swagger/**
    - /webjars/**
    - /v2/api-docs
    - /configuration/ui
    - /boot-admin
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /wx/user/login
    - /PVVE7X4F8U.txt
    - /app/admin/login
    - /phone/login/**
    - /common/sms/**
    - /app/admin/sms/login/**
    - /app/member/phone/**
    - /common/sys/**
    - /device/**
    - /common/ocr/**



# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    #缓存开启
    cache-enabled: true
    #日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
#logging:
#  config: classpath:logback-spring.xml
#  # 输出级别
#  level:
#    root: info
#  #    org.springframework: debug
#  file:
#    # 指定路径
#    path: lili-logs
#  logback:
#    rollingpolicy:
#      # 最大保存天数
#      max-history: 7
#      # 每个文件最大大小
#      max-file-size: 5MB
#加密参数

lili:
  system:
    isDemoSite: true
  statistics:
    # 在线人数统计 X 小时。这里设置48，即统计过去48小时每小时在线人数
    onlineMember: 48
    # 当前在线人数刷新时间间隔，单位秒，设置为600，则每10分钟刷新一次
    currentOnlineUpdate: 600
  #qq lbs 申请
  lbs:
    key: 4NFBZ-ZLG6D-C3T4M-PE2NB-YFLFO-JKFEX
    sk: MxGnkWiaLeBB4POInGpVXHTLEjUYMAT
wteam:
  # jwt 细节设定
  jwt-setting:
    # token过期时间（分钟）
    tokenExpireTime: 3600

  # 使用Spring @Cacheable注解失效时间
  cache:
    # 过期时间 单位秒 永久不过期设为-1
    timeout: 1500
#
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: lili_group
#    send-message-timeout: 30000
#
#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:9001/xxl-job-admin
#    executor:
#      appname: xxl-job-executor-lilishop
#      address:
#      ip:
#      port: 8891
#      logpath: ./xxl-job/executor
#      logretentiondays: 7


